name: Build and Check Syntax

on:
  push:
    branches:
      - rm
  pull_request:
    branches:
      - rm

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release