name: .NET Framework Build and Syntax Check

on:
  push:
    branches:
      forOKFKS
pull_request:
  branches:
      forOKFKS

jobs:
  build:
    runs-on: windows-latest
    steps:
    
name: Install .NET Framework Developer Pack
    run: choco install netfx-4.7.2-devpack -y

    
name: Set up MSBuild
    uses: microsoft/setup-msbuild@v1

    
name: Build with MSBuild
    run: msbuild /p:Configuration=Release
    
name: Checkout code
    uses: actions/checkout@v3